/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreatHuntingRouteImport } from './routes/threat-hunting'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RepositoryRouteImport } from './routes/repository'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegexLabRouteImport } from './routes/regex-lab'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as LogExplorerRouteImport } from './routes/log-explorer'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as CorrelationRouteImport } from './routes/correlation'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'

const ThreatHuntingRoute = ThreatHuntingRouteImport.update({
  id: '/threat-hunting',
  path: '/threat-hunting',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryRoute = RepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegexLabRoute = RegexLabRouteImport.update({
  id: '/regex-lab',
  path: '/regex-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const LogExplorerRoute = LogExplorerRouteImport.update({
  id: '/log-explorer',
  path: '/log-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrelationRoute = CorrelationRouteImport.update({
  id: '/correlation',
  path: '/correlation',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRoute
  '/correlation': typeof CorrelationRoute
  '/dashboards': typeof DashboardsRoute
  '/generator': typeof GeneratorRoute
  '/integrations': typeof IntegrationsRoute
  '/log-explorer': typeof LogExplorerRoute
  '/playbooks': typeof PlaybooksRoute
  '/regex-lab': typeof RegexLabRoute
  '/reports': typeof ReportsRoute
  '/repository': typeof RepositoryRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/threat-hunting': typeof ThreatHuntingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRoute
  '/correlation': typeof CorrelationRoute
  '/dashboards': typeof DashboardsRoute
  '/generator': typeof GeneratorRoute
  '/integrations': typeof IntegrationsRoute
  '/log-explorer': typeof LogExplorerRoute
  '/playbooks': typeof PlaybooksRoute
  '/regex-lab': typeof RegexLabRoute
  '/reports': typeof ReportsRoute
  '/repository': typeof RepositoryRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/threat-hunting': typeof ThreatHuntingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRoute
  '/correlation': typeof CorrelationRoute
  '/dashboards': typeof DashboardsRoute
  '/generator': typeof GeneratorRoute
  '/integrations': typeof IntegrationsRoute
  '/log-explorer': typeof LogExplorerRoute
  '/playbooks': typeof PlaybooksRoute
  '/regex-lab': typeof RegexLabRoute
  '/reports': typeof ReportsRoute
  '/repository': typeof RepositoryRoute
  '/settings': typeof SettingsRoute
  '/tags': typeof TagsRoute
  '/threat-hunting': typeof ThreatHuntingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/ai-assistant'
    | '/alerts'
    | '/cases'
    | '/correlation'
    | '/dashboards'
    | '/generator'
    | '/integrations'
    | '/log-explorer'
    | '/playbooks'
    | '/regex-lab'
    | '/reports'
    | '/repository'
    | '/settings'
    | '/tags'
    | '/threat-hunting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/ai-assistant'
    | '/alerts'
    | '/cases'
    | '/correlation'
    | '/dashboards'
    | '/generator'
    | '/integrations'
    | '/log-explorer'
    | '/playbooks'
    | '/regex-lab'
    | '/reports'
    | '/repository'
    | '/settings'
    | '/tags'
    | '/threat-hunting'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/ai-assistant'
    | '/alerts'
    | '/cases'
    | '/correlation'
    | '/dashboards'
    | '/generator'
    | '/integrations'
    | '/log-explorer'
    | '/playbooks'
    | '/regex-lab'
    | '/reports'
    | '/repository'
    | '/settings'
    | '/tags'
    | '/threat-hunting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AlertsRoute: typeof AlertsRoute
  CasesRoute: typeof CasesRoute
  CorrelationRoute: typeof CorrelationRoute
  DashboardsRoute: typeof DashboardsRoute
  GeneratorRoute: typeof GeneratorRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LogExplorerRoute: typeof LogExplorerRoute
  PlaybooksRoute: typeof PlaybooksRoute
  RegexLabRoute: typeof RegexLabRoute
  ReportsRoute: typeof ReportsRoute
  RepositoryRoute: typeof RepositoryRoute
  SettingsRoute: typeof SettingsRoute
  TagsRoute: typeof TagsRoute
  ThreatHuntingRoute: typeof ThreatHuntingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threat-hunting': {
      id: '/threat-hunting'
      path: '/threat-hunting'
      fullPath: '/threat-hunting'
      preLoaderRoute: typeof ThreatHuntingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository': {
      id: '/repository'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof RepositoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex-lab': {
      id: '/regex-lab'
      path: '/regex-lab'
      fullPath: '/regex-lab'
      preLoaderRoute: typeof RegexLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-explorer': {
      id: '/log-explorer'
      path: '/log-explorer'
      fullPath: '/log-explorer'
      preLoaderRoute: typeof LogExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correlation': {
      id: '/correlation'
      path: '/correlation'
      fullPath: '/correlation'
      preLoaderRoute: typeof CorrelationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AiAssistantRoute: AiAssistantRoute,
  AlertsRoute: AlertsRoute,
  CasesRoute: CasesRoute,
  CorrelationRoute: CorrelationRoute,
  DashboardsRoute: DashboardsRoute,
  GeneratorRoute: GeneratorRoute,
  IntegrationsRoute: IntegrationsRoute,
  LogExplorerRoute: LogExplorerRoute,
  PlaybooksRoute: PlaybooksRoute,
  RegexLabRoute: RegexLabRoute,
  ReportsRoute: ReportsRoute,
  RepositoryRoute: RepositoryRoute,
  SettingsRoute: SettingsRoute,
  TagsRoute: TagsRoute,
  ThreatHuntingRoute: ThreatHuntingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
